import { describe, expect, it } from 'vitest';
import { DEFAULT_TUNABLES, SKILL_TABLE, asId, type PlayerId, type SessionId } from '@alderfell/shared';
import { PlayerService } from '../domain/player-service.js';
import { RegistryCommandRouter } from '../net/gateway.js';
import { registerCombatHandlers } from '../net/handlers/combat.js';
import { InMemoryPlayerRepository } from '../persistence/repository.js';
import type { Session } from '../session/session-store.js';
const PLAYER = asId<PlayerId>('combat-player'); const WISP = 'int.duel.training_wisp'; const ARCANE_WISP = 'int.duel.arcane_wisp';
function session(): Session { return { id: asId<SessionId>('combat-session'), playerId: PLAYER, resumeToken: 'combat-token', createdAtMs: 0, disconnectedAtMs: null, lastClientSeq: 0 }; }
function harness() { let clock=1_000_000; let position:{x:number;z:number}|null={x:0,z:12.8}; const players=new PlayerService({repository:new InMemoryPlayerRepository(()=>clock),slotCapacity:DEFAULT_TUNABLES.gathering.baseInventorySlots,now:()=>clock}); const router=new RegistryCommandRouter(); registerCombatHandlers(router,{players,now:()=>clock,tickMs:DEFAULT_TUNABLES.combat.tickMs,interactionRadius:DEFAULT_TUNABLES.world.interactionRadius,currencyCap:DEFAULT_TUNABLES.economy.currencyCap,skills:SKILL_TABLE,progression:DEFAULT_TUNABLES.progression,combatXpPerDamage:DEFAULT_TUNABLES.combat.combatXpPerDamage,positionFor:()=>position}); return {dispatch:(interactableId=WISP)=>router.dispatch(session(),'combat.attack',{interactableId}),recover:()=>router.dispatch(session(),'combat.recover',{}),moveTo:(p:{x:number;z:number}|null)=>{position=p;},advance:(ms:number)=>{clock+=ms;},async state(){const r=await players.load(PLAYER);if(!r.ok)throw Error(r.error.reason);return r.value;}};}
describe('practice combat handlers',()=>{it('rejects remote attacks',async()=>{const h=harness();h.moveTo({x:20,z:20});const r=await h.dispatch();expect(r.ok).toBe(false);if(!r.ok)expect(r.error.reason).toBe('combat.out_of_range');});it('gates the higher tier behind Combat level two',async()=>{const h=harness();h.moveTo({x:-4,z:17.5});const r=await h.dispatch(ARCANE_WISP);expect(r.ok).toBe(false);if(!r.ok)expect(r.error.reason).toBe('combat.level_required');});it('awards confirmed Combat XP',async()=>{const h=harness();expect(await h.dispatch()).toMatchObject({ok:true,value:{combat:{damage:1,combatXpGained:4}}});expect((await h.state()).skills['skill.combat']).toEqual({level:1,xp:4});});it('enforces cooldowns',async()=>{const h=harness();await h.dispatch();const r=await h.dispatch();expect(r.ok).toBe(false);if(!r.ok)expect(r.error.reason).toBe('combat.cooldown');h.advance(DEFAULT_TUNABLES.combat.tickMs);expect((await h.dispatch()).ok).toBe(true);});it('rewards defeat and gates recovery',async()=>{const h=harness();let result:unknown;for(let i=0;i<8;i+=1){result=await h.dispatch();h.advance(DEFAULT_TUNABLES.combat.tickMs);}expect(result).toMatchObject({ok:true,value:{combat:{defeated:true,coinsGained:6}}});expect((await h.state()).skills['skill.combat']).toEqual({level:1,xp:32});h.advance(4_000);for(let i=0;i<3;i+=1){await h.dispatch();h.advance(DEFAULT_TUNABLES.combat.tickMs);}expect((await h.state()).hitpoints.current).toBe(0);expect((await h.recover()).ok).toBe(false);h.advance(5_000);expect((await h.recover()).ok).toBe(true);});});